#Hi

In [1]:
# Create a Series from a list [10, 20, 30, 40] with custom index.

from pandas import Series
S1=Series([10,20,30,40],index=["Index 1","Index 2","Index 3","Index 4"])
S1

Index 1    10
Index 2    20
Index 3    30
Index 4    40
dtype: int64

In [2]:
# Create a DataFrame with columns: Name, Age, Salary.

from pandas import DataFrame

Df1 = DataFrame({
    "Name": [f"Name{i}" for i in range(1, 21)],
    "Age": [20 + (i % 30) for i in range(20)],
    "Salary": [30000 + i * 1000 for i in range(20)]
})
Df1

      Name  Age  Salary
0    Name1   20   30000
1    Name2   21   31000
2    Name3   22   32000
3    Name4   23   33000
4    Name5   24   34000
5    Name6   25   35000
6    Name7   26   36000
7    Name8   27   37000
8    Name9   28   38000
9   Name10   29   39000
10  Name11   30   40000
11  Name12   31   41000
12  Name13   32   42000
13  Name14   33   43000
14  Name15   34   44000
15  Name16   35   45000
16  Name17   36   46000
17  Name18   37   47000
18  Name19   38   48000
19  Name20   39   49000

In [3]:
# Change the column names of a DataFrame.

Df1.columns=["Employee name","Years","Income"]
Df1

   Employee name  Years  Income
0          Name1     20   30000
1          Name2     21   31000
2          Name3     22   32000
3          Name4     23   33000
4          Name5     24   34000
5          Name6     25   35000
6          Name7     26   36000
7          Name8     27   37000
8          Name9     28   38000
9         Name10     29   39000
10        Name11     30   40000
11        Name12     31   41000
12        Name13     32   42000
13        Name14     33   43000
14        Name15     34   44000
15        Name16     35   45000
16        Name17     36   46000
17        Name18     37   47000
18        Name19     38   48000
19        Name20     39   49000

In [4]:
# Select a single column using two different methods.
Df1.loc[:]["Employee name"]
Df1.iloc[:]["Years"]

0     20
1     21
2     22
3     23
4     24
5     25
6     26
7     27
8     28
9     29
10    30
11    31
12    32
13    33
14    34
15    35
16    36
17    37
18    38
19    39
Name: Years, dtype: int64

In [5]:
# Select multiple columns.  
Df1.loc[:,["Employee name","Income"]]

   Employee name  Income
0          Name1   30000
1          Name2   31000
2          Name3   32000
3          Name4   33000
4          Name5   34000
5          Name6   35000
6          Name7   36000
7          Name8   37000
8          Name9   38000
9         Name10   39000
10        Name11   40000
11        Name12   41000
12        Name13   42000
13        Name14   43000
14        Name15   44000
15        Name16   45000
16        Name17   46000
17        Name18   47000
18        Name19   48000
19        Name20   49000

In [6]:
# Retrieve first 5 rows.
Df1.head(5)

  Employee name  Years  Income
0         Name1     20   30000
1         Name2     21   31000
2         Name3     22   32000
3         Name4     23   33000
4         Name5     24   34000

In [7]:
# Retrieve last 3 rows.
Df1.tail(3)

   Employee name  Years  Income
17        Name18     37   47000
18        Name19     38   48000
19        Name20     39   49000

In [8]:
# Find datatype of each column.
Df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee name  20 non-null     str
 1   Years          20 non-null     int64
 2   Income         20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

In [9]:
# Use describe() on numeric columns.
Df1.loc[:,["Years","Income"]].describe()

          Years        Income
count  20.00000     20.000000
mean   29.50000  39500.000000
std     5.91608   5916.079783
min    20.00000  30000.000000
25%    24.75000  34750.000000
50%    29.50000  39500.000000
75%    34.25000  44250.000000
max    39.00000  49000.000000

In [10]:
# Set a custom index using a column.
Df1.index=[i for i in range(11,31)]
Df1

   Employee name  Years  Income
11         Name1     20   30000
12         Name2     21   31000
13         Name3     22   32000
14         Name4     23   33000
15         Name5     24   34000
16         Name6     25   35000
17         Name7     26   36000
18         Name8     27   37000
19         Name9     28   38000
20        Name10     29   39000
21        Name11     30   40000
22        Name12     31   41000
23        Name13     32   42000
24        Name14     33   43000
25        Name15     34   44000
26        Name16     35   45000
27        Name17     36   46000
28        Name18     37   47000
29        Name19     38   48000
30        Name20     39   49000

In [11]:
# Select rows where Age > 25
Df1.loc[Df1.Years>29,"Years"]

21    30
22    31
23    32
24    33
25    34
26    35
27    36
28    37
29    38
30    39
Name: Years, dtype: int64

In [12]:
# Select rows where Salary < 50000.
Df1.loc[Df1.Income<37000,"Income"]

11    30000
12    31000
13    32000
14    33000
15    34000
16    35000
17    36000
Name: Income, dtype: int64

In [13]:
# Select rows with multiple conditions (Age > 25 AND Salary > 40000).
Df1.loc[(Df1.Income<37000) & (Df1.Years<29),"Income"]

11    30000
12    31000
13    32000
14    33000
15    34000
16    35000
17    36000
Name: Income, dtype: int64

In [75]:
# Reset index.
Df1.reset_index(drop=True)

# Df1.drop(columns=["index"])

      Name  Years  Salary  New_salary        log  Normalized_salary categories
0    Name1     20       1       40000  10.308986           0.000000        Low
1    Name2     21   31000       41000  10.341775           0.052632        Low
2    Name3     22   32000       42000  10.373522           0.105263        Low
3    Name4     23   33000       43000  10.404293           0.157895        Low
4    Name5     24   34000       44000  10.434145           0.210526        Low
5    Name6     25   35000       45000  10.463132           0.263158        Low
6    Name7     26   36000       46000  10.491302           0.315789     Medium
7    Name8     27   37000       47000  10.518700           0.368421     Medium
8    Name9     28   38000       48000  10.545368           0.421053     Medium
9   Name10     29   39000       49000  10.571343           0.473684     Medium
10  Name11     30   40000       50000  10.596660           0.526316     Medium
11  Name12     31   41000       51000  10.621352           0.578947     Medium
12  Name13     32   42000       52000  10.645449           0.631579     Medium
13  Name14     33   43000       53000  10.668979           0.684211       High
14  Name15     34   44000       54000  10.691968           0.736842       High
15  Name16     35   45000       55000  10.714440           0.789474       High
16  Name17     36   46000       56000  10.736418           0.842105       High
17  Name18     37   47000       57000  10.757924           0.894737       High
18  Name19     38   48000       58000  10.778977           0.947368       High
19  Name20     39   49000       59000  10.799596           1.000000       High

In [15]:
# Sort data using sort_index().
Df1.sort_index(axis=0,ascending=False)

   Employee name  Years  Income
30        Name20     39   49000
29        Name19     38   48000
28        Name18     37   47000
27        Name17     36   46000
26        Name16     35   45000
25        Name15     34   44000
24        Name14     33   43000
23        Name13     32   42000
22        Name12     31   41000
21        Name11     30   40000
20        Name10     29   39000
19         Name9     28   38000
18         Name8     27   37000
17         Name7     26   36000
16         Name6     25   35000
15         Name5     24   34000
14         Name4     23   33000
13         Name3     22   32000
12         Name2     21   31000
11         Name1     20   30000

In [16]:
Df1.duplicated()

11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
dtype: bool

In [17]:
# Remove duplicate rows.
Df1.drop_duplicates()

   Employee name  Years  Income
11         Name1     20   30000
12         Name2     21   31000
13         Name3     22   32000
14         Name4     23   33000
15         Name5     24   34000
16         Name6     25   35000
17         Name7     26   36000
18         Name8     27   37000
19         Name9     28   38000
20        Name10     29   39000
21        Name11     30   40000
22        Name12     31   41000
23        Name13     32   42000
24        Name14     33   43000
25        Name15     34   44000
26        Name16     35   45000
27        Name17     36   46000
28        Name18     37   47000
29        Name19     38   48000
30        Name20     39   49000

In [18]:
# Keep only first occurrence of duplicates.
Df1.drop_duplicates(keep='first')

   Employee name  Years  Income
11         Name1     20   30000
12         Name2     21   31000
13         Name3     22   32000
14         Name4     23   33000
15         Name5     24   34000
16         Name6     25   35000
17         Name7     26   36000
18         Name8     27   37000
19         Name9     28   38000
20        Name10     29   39000
21        Name11     30   40000
22        Name12     31   41000
23        Name13     32   42000
24        Name14     33   43000
25        Name15     34   44000
26        Name16     35   45000
27        Name17     36   46000
28        Name18     37   47000
29        Name19     38   48000
30        Name20     39   49000

In [19]:
# Convert column datatype (int → string).
Df1["Income"].astype("U")

11    30000
12    31000
13    32000
14    33000
15    34000
16    35000
17    36000
18    37000
19    38000
20    39000
21    40000
22    41000
23    42000
24    43000
25    44000
26    45000
27    46000
28    47000
29    48000
30    49000
Name: Income, dtype: object

In [20]:
Df1.columns=["Name","Years","Salary"]
Df1

      Name  Years  Salary
11   Name1     20   30000
12   Name2     21   31000
13   Name3     22   32000
14   Name4     23   33000
15   Name5     24   34000
16   Name6     25   35000
17   Name7     26   36000
18   Name8     27   37000
19   Name9     28   38000
20  Name10     29   39000
21  Name11     30   40000
22  Name12     31   41000
23  Name13     32   42000
24  Name14     33   43000
25  Name15     34   44000
26  Name16     35   45000
27  Name17     36   46000
28  Name18     37   47000
29  Name19     38   48000
30  Name20     39   49000

In [21]:
Df1.loc[Df1.Salary>39000]["Salary"]

21    40000
22    41000
23    42000
24    43000
25    44000
26    45000
27    46000
28    47000
29    48000
30    49000
Name: Salary, dtype: int64

In [25]:
# Create a new column based on existing ones.
Df1["New_salary"]=Df1.Salary+10000
Df1.drop(columns=["Salary"])

      Name  Years  New_salary
11   Name1     20       40000
12   Name2     21       41000
13   Name3     22       42000
14   Name4     23       43000
15   Name5     24       44000
16   Name6     25       45000
17   Name7     26       46000
18   Name8     27       47000
19   Name9     28       48000
20  Name10     29       49000
21  Name11     30       50000
22  Name12     31       51000
23  Name13     32       52000
24  Name14     33       53000
25  Name15     34       54000
26  Name16     35       55000
27  Name17     36       56000
28  Name18     37       57000
29  Name19     38       58000
30  Name20     39       59000

In [ ]:
# Apply a function to a column 
import numpy as np
from sklearn.preprocessing import FunctionTransformer
FT=FunctionTransformer(func=np.log1p)
ar=FT.fit_transform(Df1["Salary"])
Df1["log"]=Series(ar)
Df1

      Name  Years  Salary  New_salary        log
11   Name1     20   30000       40000  10.308986
12   Name2     21   31000       41000  10.341775
13   Name3     22   32000       42000  10.373522
14   Name4     23   33000       43000  10.404293
15   Name5     24   34000       44000  10.434145
16   Name6     25   35000       45000  10.463132
17   Name7     26   36000       46000  10.491302
18   Name8     27   37000       47000  10.518700
19   Name9     28   38000       48000  10.545368
20  Name10     29   39000       49000  10.571343
21  Name11     30   40000       50000  10.596660
22  Name12     31   41000       51000  10.621352
23  Name13     32   42000       52000  10.645449
24  Name14     33   43000       53000  10.668979
25  Name15     34   44000       54000  10.691968
26  Name16     35   45000       55000  10.714440
27  Name17     36   46000       56000  10.736418
28  Name18     37   47000       57000  10.757924
29  Name19     38   48000       58000  10.778977
30  Name20     39   49000       59000  10.799596

In [ ]:
# Normalize a column (scale values).
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
MML=MinMaxScaler()
ar=MML.fit_transform(Df1[["Salary"]])
Df1["Normalized_salary"]=ar.flatten()
Df1
# sns.boxplot(x="Salary",data=Df1)
# plt.show()

      Name  Years  Salary  New_salary        log  Normalized_salary
11   Name1     20   30000       40000  10.308986           0.000000
12   Name2     21   31000       41000  10.341775           0.052632
13   Name3     22   32000       42000  10.373522           0.105263
14   Name4     23   33000       43000  10.404293           0.157895
15   Name5     24   34000       44000  10.434145           0.210526
16   Name6     25   35000       45000  10.463132           0.263158
17   Name7     26   36000       46000  10.491302           0.315789
18   Name8     27   37000       47000  10.518700           0.368421
19   Name9     28   38000       48000  10.545368           0.421053
20  Name10     29   39000       49000  10.571343           0.473684
21  Name11     30   40000       50000  10.596660           0.526316
22  Name12     31   41000       51000  10.621352           0.578947
23  Name13     32   42000       52000  10.645449           0.631579
24  Name14     33   43000       53000  10.668979           0.684211
25  Name15     34   44000       54000  10.691968           0.736842
26  Name16     35   45000       55000  10.714440           0.789474
27  Name17     36   46000       56000  10.736418           0.842105
28  Name18     37   47000       57000  10.757924           0.894737
29  Name19     38   48000       58000  10.778977           0.947368
30  Name20     39   49000       59000  10.799596           1.000000

In [ ]:
# Categorize data (e.g., Salary → Low/Medium/High).
Df1["categories"]="Low"
Df1.loc[(Df1.Salary>35000)&(Df1.Salary<43000),"categories"]="Medium"
Df1.loc[Df1.Salary>=43000,"categories"]="High"
Df1

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20   30000       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [51]:
# Identify missing values.
# Df1.shape
# Df1.isnull().sum()
# (Df1.isnull().sum()/Df1.shape[0])*100
Df1.isnull().sum().sum()
(Df1.isnull().sum()/Df1.shape[0]*Df1.shape[1])*100

Name                 0.0
Years                0.0
Salary               0.0
New_salary           0.0
log                  0.0
Normalized_salary    0.0
categories           0.0
dtype: float64

In [52]:
# Fill missing values with 0.
Df1.fillna(0)

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20   30000       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [59]:
# Fill missing values with column mean.
Df1["Salary"].fillna(Df1["Salary"].mean(),inplace=True)

/tmp/ipykernel_3919/1124265058.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  Df1["Salary"].fillna(Df1["Salary"].mean(),inplace=True)

11    30000
12    31000
13    32000
14    33000
15    34000
16    35000
17    36000
18    37000
19    38000
20    39000
21    40000
22    41000
23    42000
24    43000
25    44000
26    45000
27    46000
28    47000
29    48000
30    49000
Name: Salary, dtype: int64

In [63]:
# Fill missing values with forward fill.
Df1["Salary"]=Df1.Salary.ffill()
Df1

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20   30000       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [65]:
# Drop rows with any missing value.
Df1.dropna(axis=0)

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20   30000       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [66]:
# Drop cloumns with any missing value.
Df1.dropna(axis=1)

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20   30000       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [87]:
# Replace specific values (e.g., "NA" → NaN).
Df1.loc[11,"Name"]="NA"
Df1["Name"] = Df1["Name"].replace("NA", None)
Df1

,Name,Years,Salary,New_salary,log,Normalized_salary,categories
11,NaN,20,NaN,40000,10.308986,0.000000,Low
12,Name2,21,31000.0,41000,10.341775,0.052632,Low
13,Name3,22,32000.0,42000,10.373522,0.105263,Low
14,Name4,23,33000.0,43000,10.404293,0.157895,Low
15,Name5,24,34000.0,44000,10.434145,0.210526,Low
16,Name6,25,35000.0,45000,10.463132,0.263158,Low
17,Name7,26,36000.0,46000,10.491302,0.315789,Medium
18,Name8,27,37000.0,47000,10.518700,0.368421,Medium
19,Name9,28,38000.0,48000,10.545368,0.421053,Medium
20,Name10,29,39000.0,49000,10.571343,0.473684,Medium
21,Name11,30,40000.0,50000,10.596660,0.526316,Medium
22,Name12,31,41000.0,51000,10.621352,0.578947,Medium
23,Name13,32,42000.0,52000,10.645449,0.631579,Medium
24,Name14,33,43000.0,53000,10.668979,0.684211,High
25,Name15,34,44000.0,54000,10.691968,0.736842,High
26,Name16,35,45000.0,55000,10.714440,0.789474,High
27,Name17,36,46000.0,56000,10.736418,0.842105,High
28,Name18,37,47000.0,57000,10.757924,0.894737,High
29,Name19,38,48000.0,58000,10.778977,0.947368,High
30,Name20,39,49000.0,59000,10.799596,1.000000,High

In [76]:
# Replace multiple values at once.
Df1.dropna(subset=["Salary","Name"])

      Name  Years  Salary  New_salary        log  Normalized_salary categories
11   Name1     20       1       40000  10.308986           0.000000        Low
12   Name2     21   31000       41000  10.341775           0.052632        Low
13   Name3     22   32000       42000  10.373522           0.105263        Low
14   Name4     23   33000       43000  10.404293           0.157895        Low
15   Name5     24   34000       44000  10.434145           0.210526        Low
16   Name6     25   35000       45000  10.463132           0.263158        Low
17   Name7     26   36000       46000  10.491302           0.315789     Medium
18   Name8     27   37000       47000  10.518700           0.368421     Medium
19   Name9     28   38000       48000  10.545368           0.421053     Medium
20  Name10     29   39000       49000  10.571343           0.473684     Medium
21  Name11     30   40000       50000  10.596660           0.526316     Medium
22  Name12     31   41000       51000  10.621352           0.578947     Medium
23  Name13     32   42000       52000  10.645449           0.631579     Medium
24  Name14     33   43000       53000  10.668979           0.684211       High
25  Name15     34   44000       54000  10.691968           0.736842       High
26  Name16     35   45000       55000  10.714440           0.789474       High
27  Name17     36   46000       56000  10.736418           0.842105       High
28  Name18     37   47000       57000  10.757924           0.894737       High
29  Name19     38   48000       58000  10.778977           0.947368       High
30  Name20     39   49000       59000  10.799596           1.000000       High

In [88]:
# Fill missing values differently for each column.
Df1.fillna({"Name":"Op","Salary":Df1["Salary"].mean()})

,Name,Years,Salary,New_salary,log,Normalized_salary,categories
11,Op,20,40000.0,40000,10.308986,0.000000,Low
12,Name2,21,31000.0,41000,10.341775,0.052632,Low
13,Name3,22,32000.0,42000,10.373522,0.105263,Low
14,Name4,23,33000.0,43000,10.404293,0.157895,Low
15,Name5,24,34000.0,44000,10.434145,0.210526,Low
16,Name6,25,35000.0,45000,10.463132,0.263158,Low
17,Name7,26,36000.0,46000,10.491302,0.315789,Medium
18,Name8,27,37000.0,47000,10.518700,0.368421,Medium
19,Name9,28,38000.0,48000,10.545368,0.421053,Medium
20,Name10,29,39000.0,49000,10.571343,0.473684,Medium
21,Name11,30,40000.0,50000,10.596660,0.526316,Medium
22,Name12,31,41000.0,51000,10.621352,0.578947,Medium
23,Name13,32,42000.0,52000,10.645449,0.631579,Medium
24,Name14,33,43000.0,53000,10.668979,0.684211,High
25,Name15,34,44000.0,54000,10.691968,0.736842,High
26,Name16,35,45000.0,55000,10.714440,0.789474,High
27,Name17,36,46000.0,56000,10.736418,0.842105,High
28,Name18,37,47000.0,57000,10.757924,0.894737,High
29,Name19,38,48000.0,58000,10.778977,0.947368,High
30,Name20,39,49000.0,59000,10.799596,1.000000,High

In [89]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 200

df = pd.DataFrame({
    "EmployeeID": np.arange(1001, 1001+n),
    "Name": np.random.choice(["Amit", "Sara", "John", "Priya", "Ali", "Ravi"], n),
    "Age": np.random.randint(21, 60, n),
    "Department": np.random.choice(["IT", "HR", "Finance", "Sales"], n),
    "Salary": np.random.randint(20000, 120000, n),
    "Experience": np.random.randint(0, 20, n),
    "City": np.random.choice(["Delhi", "Mumbai", "Bangalore", "Kolkata"], n),
    "JoiningYear": np.random.randint(2005, 2023, n),
    "PerformanceScore": np.random.randint(1, 10, n),
    "Bonus": np.random.randint(5000, 30000, n),
    "ProjectsHandled": np.random.randint(1, 15, n),
    "Attrition": np.random.choice(["Yes", "No"], n)
})
# Randomly introduce nulls
for col in ["Age", "Salary", "Bonus"]:
    df.loc[df.sample(frac=0.1).index, col] = np.nan
# Add salary outliers
outlier_indices = df.sample(5).index
df.loc[outlier_indices, "Salary"] = df["Salary"] * 5

# Add bonus outliers
outlier_indices = df.sample(5).index
df.loc[outlier_indices, "Bonus"] = df["Bonus"] * 4
df2 = pd.DataFrame({
    "EmployeeID": np.random.choice(df["EmployeeID"], 150),
    "BankAccount": np.random.randint(10000000, 99999999, 150),
    "LoanAmount": np.random.randint(10000, 500000, 150),
    "CreditScore": np.random.randint(300, 900, 150)
})
df2 = pd.DataFrame({
    "EmployeeID": np.random.choice(df["EmployeeID"], 150),
    "BankAccount": np.random.randint(10000000, 99999999, 150),
    "LoanAmount": np.random.randint(10000, 500000, 150),
    "CreditScore": np.random.randint(300, 900, 150)
})
df.to_csv("employees.csv", index=False)
df2.to_csv("financials.csv", index=False)

In [3]:
import pandas as pd
df1 = pd.read_csv("employees.csv")
df2 = pd.read_csv("financials.csv")

In [10]:
pd.merge(df1,df2,on="EmployeeID")
pd.merge(df1,df2,how="inner")
pd.merge(df1,df2,how="right")
pd.merge(df1,df2,how="left")
pd.merge(df1,df2,how="outer")

pd.concat([df1,df2],axis=1)
pd.concat([df1,df2],axis=0)

df1.join(df2,lsuffix="LEFT",rsuffix="RIGHT")

pd.concat([df1,df2],ignore_index=True)

pd.merge(df1,df2,how="inner")

,EmployeeID,Name,Age,Department,Salary,Experience,City,JoiningYear,PerformanceScore,Bonus,ProjectsHandled,Attrition,BankAccount,LoanAmount,CreditScore
0,1002,Ali,52.0,HR,79163.0,8,Kolkata,2009,6,19749.0,6,No,63230681,29991,377
1,1003,John,44.0,Finance,NaN,13,Delhi,2012,2,16718.0,10,Yes,57623905,267927,776
2,1004,Ali,32.0,HR,71934.0,0,Bangalore,2014,3,26736.0,6,No,67675376,38884,703
3,1007,John,23.0,IT,74098.0,12,Mumbai,2018,1,6435.0,9,Yes,50339104,320001,612
4,1007,John,23.0,IT,74098.0,12,Mumbai,2018,1,6435.0,9,Yes,52635177,55475,396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,1188,Amit,25.0,IT,NaN,3,Mumbai,2013,2,23440.0,1,Yes,49944891,282872,447
146,1195,Amit,36.0,Sales,89172.0,14,Bangalore,2014,1,18629.0,5,Yes,64633048,227583,690
147,1199,John,37.0,Sales,NaN,4,Kolkata,2022,3,18395.0,14,No,44590323,325018,773
148,1200,Ravi,39.0,IT,33456.0,10,Kolkata,2009,6,5207.0,12,Yes,11901740,40106,858
149,1200,Ravi,39.0,IT,33456.0,10,Kolkata,2009,6,5207.0,12,Yes,36372008,305064,885

In [15]:
# Group by department and find average salary.
a=df1.groupby("Department")["Salary"].mean()
a

Department
Finance    61189.757576
HR         88223.975000
IT         65356.576271
Sales      74624.937500
Name: Salary, dtype: float64

In [ ]:
# Group by multiple columns.
a=df1.groupby(["Department","Salary"])["Salary"].mean()
a

Department  Salary
Finance     24158.0      24158.0
            25486.0      25486.0
            26801.0      26801.0
            27114.0      27114.0
            28335.0      28335.0
                          ...
Sales       109339.0    109339.0
            111792.0    111792.0
            113045.0    113045.0
            219800.0    219800.0
            267955.0    267955.0
Name: Salary, Length: 180, dtype: float64

In [18]:
# Count number of employees per department.
a=df1.groupby("Department")["EmployeeID"].count()
a

Department
Finance    38
HR         47
IT         63
Sales      52
Name: EmployeeID, dtype: int64

In [ ]:
# Find max salary per department.
a=df1.groupby("Department")["Salary"].max()
a

Department
Finance    117007.0
HR         597590.0
IT         119835.0
Sales      267955.0
Name: Salary, dtype: float64

In [36]:
# Create a pivot table (Dept vs Avg Salary).
b=df1.pivot_table(index="Department",columns="City",values="Salary",aggfunc="mean")
b = b.reset_index()

In [37]:
pd.melt(b,id_vars="Department",var_name="City",value_name="Salary")

   Department       City         Salary
0     Finance  Bangalore   52500.400000
1          HR  Bangalore   78870.333333
2          IT  Bangalore   69107.153846
3       Sales  Bangalore   91399.000000
4     Finance      Delhi   67079.000000
5          HR      Delhi  124422.222222
6          IT      Delhi   66240.636364
7       Sales      Delhi   67052.647059
8     Finance    Kolkata   63144.000000
9          HR    Kolkata   61681.916667
10         IT    Kolkata   59645.250000
11      Sales    Kolkata   52160.428571
12    Finance     Mumbai   64452.250000
13         HR     Mumbai   91981.076923
14         IT     Mumbai   69072.866667
15      Sales     Mumbai   71966.166667

In [42]:
# Find top 3 highest salaries.
df1.nlargest(3,"Salary")

,EmployeeID,Name,Age,Department,Salary,Experience,City,JoiningYear,PerformanceScore,Bonus,ProjectsHandled,Attrition
91,1092,Ali,55.0,HR,597590.0,14,Delhi,2009,9,24994.0,2,Yes
95,1096,Priya,24.0,Sales,267955.0,16,Bangalore,2011,5,22368.0,3,Yes
51,1052,Sara,38.0,HR,241475.0,9,Mumbai,2020,7,8342.0,7,Yes

In [57]:
# Find employees with salary above department average.
df1[df1["Salary"] > df1.groupby("Department")["Salary"].transform("mean")]

,EmployeeID,Name,Age,Department,Salary,Experience,City,JoiningYear,PerformanceScore,Bonus,ProjectsHandled,Attrition
4,1005,Ali,59.0,IT,84895.0,18,Bangalore,2021,5,14439.0,10,No
6,1007,John,23.0,IT,74098.0,12,Mumbai,2018,1,6435.0,9,Yes
10,1011,Priya,22.0,IT,106900.0,7,Delhi,2005,8,21661.0,11,No
11,1012,John,48.0,Sales,109112.0,1,Bangalore,2018,3,18507.0,2,Yes
12,1013,Ravi,43.0,IT,117203.0,7,Mumbai,2009,8,12059.0,6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
183,1184,Ravi,35.0,IT,67926.0,12,Kolkata,2015,3,29892.0,5,Yes
188,1189,John,59.0,HR,118142.0,18,Mumbai,2013,4,11917.0,7,No
190,1191,John,26.0,Finance,100642.0,0,Delhi,2021,7,5552.0,6,Yes
191,1192,Amit,52.0,Finance,70612.0,19,Bangalore,2005,2,26767.0,5,No
194,1195,Amit,36.0,Sales,89172.0,14,Bangalore,2014,1,18629.0,5,Yes